# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: João Alberto Rego
title: Data Analyst
email: joao.al.rego@gmail.com
website: www.github.com/sproogen/resume-theme

# Social links
# twitter_username: facespics
github_username:  jalrego
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: joaoalbertorego
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/CV_Photo.jpg
about_content: | # this will include new lines to allow paragraphs
  My name is João, I am a Junior Data Analyst and a technology and finance enthusiastic motivated by challenges that require analytical and design thinking.

  <mark>Creative</mark>, <mark>Communicative</mark>, <mark>Dynamic</mark> and <mark>Teamwork</mark> are some words that can be used to describe me.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
