# Site
repository: sproogen/resume-theme
favicon: images/favicon.png

# Personal info
name: João Alberto Rego
title: Data Analyst
email: joao.al.rego@gmail.com
# website: www.github.com/sproogen/resume-theme

# Social links
# twitter_username: facespics
github_username:  jalrego
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: joaoalbertorego
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/CVPhoto.jpg
about_content: | # this will include new lines to allow paragraphs
  A Junior Data Analyst and a technology and finance enthusiastic, motivated by challenges that require analytical and design thinking.

  <b>Creative</b>, <b>Communicative</b>, <b>Dynamic</b> and <b>Teamwork</b> are some words that can be used to describe me.

# Projects Section
projects_title: Technical Skills

# Experience Section
experience_title: Professional Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
   - I have done regular <b>voluteer</b> work in the National Scouts Organization and in the Food Bank for 15 years. 
     Also made part of the Lisbon Animal Shelter volunteer team for 2 years.
   
   Offwork I like to:
   - Travel
   - WorkOut

   <mark>Languages Spoken</mark>
   - <b>Portuguese</b> - Native Speaker
   - <b>English</b> - Cambridge FCE B2 Level
   - <b>Spanish</b> - B1 Spoken and Written


# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme
sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
